apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: micro-svc

spec:
  selector:
    app: etcd-sts

  ports:
    - port: 2380
      targetPort: 2380
      protocol: TCP
      name: etcd-server

    - port: 2379
      name: etcd-client
      targetPort: 2379
      protocol: TCP

  type: NodePort
