apiVersion: v1
kind: Endpoints
metadata:
  name: user-rpc-metrics
  namespace: monitoring
subsets:
  - addresses:
      - ip: 192.168.3.36
    ports:
      - name: http-9091
        port: 9091
        protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: user-rpc-metrics
  namespace: monitoring
  labels:
    app: user-rpc-metrics
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-9091
      protocol: TCP
      port: 9091
      targetPort: http-9091

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-rpc-metrics-sm
  namespace: monitoring
  labels:
    app: user-rpc-metrics
spec:
  selector:
    matchLabels:
      app: user-rpc-metrics
  endpoints:
    - port: http-9091
      interval: 10s
