apiVersion: v1
kind: Endpoints
metadata:
  name: user-api-metrics
  namespace: monitoring
subsets:
  - addresses:
      - ip: 192.168.3.36
    ports:
      - name: http-9081
        port: 9081
        protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: user-api-metrics
  namespace: monitoring
  labels:
    app: user-api-metrics
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-9081
      protocol: TCP
      port: 9081
      targetPort: http-9081

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-api-metrics-sm
  namespace: monitoring
  labels:
    app: user-api-metrics
spec:
  selector:
    matchLabels:
      app: user-api-metrics
  endpoints:
    - port: http-9081
      interval: 10s
